# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Machine Learning Algorithms - Review
tagline:          'Machine Learning Algorithms - Review'
description:      'Construction of a Github page with a review of some Machine Learning algorithms'
url:              danmartyns.github.io
baseurl:          /machine-learning-algorithms-review

# Permalinks
permalink:        pretty

author:
  name:           'Daniel Martins'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/DanMartyns/machine-learning-algorithms-review
